project:
  type: website
  output-dir: docs

website:
  title: "LECs_tumor"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - code/SNF_draft/YUMM_vs_YUMMER/vis_de.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



