project:
  type: website
  output-dir: docs

website:
  title: "LECs_tumor"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - text: "Analysis"
        menu:
          - code/SNF_draft/YUMM_vs_YUMMER/vis_de.qmd
    tools:
      - icon: github
        menu:
          - text: Source Code
            url:  https://github.com/almutlue/LECs_tumor

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



